# 1. 这里必须换成你自己的 Cloudflare 网址
# (比如 https://my-blog-123.pages.dev，如果不确定就先填这个，后面去 Cloudflare 看一眼)
baseurl = "https://my-blog-enu.pages.dev/"

# 2. 语言设置
languageCode = "zh-cn"
title = "皮的猫's blog"
defaultContentLanguage = "zh-cn"

# 3. 【关键】开启中文支持 (CJK = 中日韩)
# 开启后，字数统计和摘要截取才会正常
hasCJKLanguage = true

[pagination]
pagerSize = 5