baseurl = "https://my-blog-enu.pages.dev/"
title = "皮的猫's blog"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

# 【核武器】强制禁用英文，Hugo 绝对不会再加载英文菜单了
disableLanguages = ["en"]

[pagination]
    pagerSize = 5

# 这里直接定义中文环境
[languages]
    [languages.zh-cn]
        languageName = "Chinese"
        weight = 1
        title = "皮的猫's blog"
        contentDir = "content"
        
        [languages.zh-cn.params]
            sidebar = "left"