# --- 左侧主菜单配置 ---

# 1. 主页
[[main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 1
    params = { icon = "home" }

# 2. 关于 (About)
[[main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2
    params = { icon = "user" }

# 3. 文章 (归档)
[[main]]
    identifier = "archives"
    name = "文章"
    url = "/archives/"
    weight = 3
    params = { icon = "box" }

# 4. 搜索
[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 4
    params = { icon = "search" }

# 5. 友链
[[main]]
    identifier = "links"
    name = "友链"
    url = "/links/"
    weight = 5
    params = { icon = "link" }
